//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_VSE_CSS475.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHistory
    {
        public int UserHistroryId { get; set; }
        public int userID { get; set; }
        public int TicketID { get; set; }
        public string PerformanceName { get; set; }
    
        public virtual Performance Performance { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
    }
}
